---

- hosts: localhost
  gather_facts: yes
  become: yes
  
  roles:
    - stefangweichinger.ansible_rclone

  tasks:
    - name: Check if rclone.service exists
      stat:
        path: "/etc/systemd/system/rclone.service"
      register: rclone_service

    - name: update database
      shell:
        cmd: |
          sqlite3 {{ settings.db }} << EOF
              REPLACE INTO APPLICATIONS (appname, status_id)
              VALUES
              ('rclone',
              (SELECT status_id FROM APPLICATION_STATUS WHERE value='Installed'));
          EOF
      when: rclone_service.stat.exists