---
- name: Check ssh_users_group
  fail:
    msg: "ssh_users_group is not valid."
  when: 
    ssh_users_group is undefined or
    ssh_users_group is not string or
    ssh_users_group | length < 1 or
    not ssh_users_group is match("^[a-zA-Z0-9_]+$")

- name: Check that ssh_users is defined
  fail:
    msg: "'ssh_users' is not valid"
  when:
    ssh_users is undefined or
    ssh_users is not iterable

- name: Check that sssh_authorized_keys_file is valid
  fail:
    msg: "'ssh_authorized_keys_file' is not valid"
  when:
    ssh_authorized_keys_file is undefined or
    ssh_authorized_keys_file | dirname is not string or ssh_authorized_keys_file | dirname | length < 1 or
    ssh_authorized_keys_file | basename | length < 1

- name: Check each user
  include_tasks: assert_users.yml
  loop: "{{ ssh_users }}"
  loop_control:
    loop_var: item