---
- name: Set user
  set_fact:
    ssh_users_user: "{{ (ansible_connection == 'local') | ternary(lookup('env','USER'), ansible_user) }}"

- name: Assert data are present
  ansible.builtin.include_tasks: assert.yml

- name: Create ssh_group
  ansible.builtin.group:
    name: "{{ ssh_users_group }}"
    state: present

- name: Set each user
  include_tasks: set_user.yml
  loop: "{{ ssh_users }}"
  loop_control:
    loop_var: item
    label: "{{ ssh_users_user }}"