---
- name: Create user {{ (item.name == 'current_user') | ternary(ssh_users_user, item.name) }}
  ansible.builtin.user:
    name: "{{ (item.name == 'current_user') | ternary(ssh_users_user, item.name) }}"
    groups: "{{ ssh_users_group }}"
    append: yes
    password: "{{ item.password | default(omit) }}"
    create_home: "{{ item.create_home | default(omit) }}"
    hidden: "{{ item.hidden_user | default(omit) }}"

- name: Create file to store sshd authorized keys
  file:
    path: "{{ ssh_authorized_keys_file }}"
    state: touch
    owner: "{{ ssh_users_user }}"
    group: "{{ ssh_users_group }}"
    mode: '0660'

- name: Run task is public_key is a direct string
  include_tasks: set_ssh_key_string.yml
  loop: "{{ item.public_keys }}"
  loop_control:
    loop_var: pkey
    label: ""
  when: pkey is match('^ssh')

- name: Run task is public_key is a local file
  include_tasks: set_ssh_key_local.yml
  loop: "{{ item.public_keys }}"
  loop_control:
    loop_var: pkey
    label: ""
  when: pkey is match('^local:')

- name: Run task is public_key is a remote file
  include_tasks: set_ssh_key_remote.yml
  loop: "{{ item.public_keys }}"
  loop_control:
    loop_var: pkey
    label: ""
  when: pkey is match('^remote')
