---
- hosts: all
  become: yes

  tasks:
  
    - name: Copy defaults
      ansible.builtin.copy:
        src: "{{ settings.roles }}/hardening/os/defaults/main.yml"
        dest: "{{ settings.collections }}/devsec/hardening/roles/os_hardening/defaults/main.yml"

    - name: Launch role after copying config
      include_role:
        name: devsec.hardening.os_hardening
    
    - name: Update database (success)
      shell:
        cmd: |
          sqlite3 {{ settings.db }} << EOF
              REPLACE INTO APPLICATIONS (appname, status_id)
              VALUES
              ('os',
              (SELECT status_id FROM APPLICATION_STATUS WHERE value='Configured'));
          EOF