---
- hosts: all
  become: yes

  roles:
    - geerlingguy.docker
  tasks:
    - name: wait for docker service
      service:
        name: docker
        state: started 
      register: docker_service
      until: docker_service.status.ActiveState == "active"
      retries: 3
      delay: 3

    - name: Update database (success)
      shell:
        cmd: |
          sqlite3 {{ settings.db }} << EOF
              REPLACE INTO APPLICATIONS (appname, status_id)
              VALUES
              ('docker',
              (SELECT status_id FROM APPLICATION_STATUS WHERE value='Installed'));
          EOF